### ISSUE TITLE
Error when initializing

### ISSUE THREAD

**Issue by SnooHD** [miguelmota/Navigator.sendBeacon#16]
Getting an error when doing `import sendBeacon from 'Navigator.sendBeacon'`
Am i doing something wrong here?

Thanks

```
✖ error TypeError: Cannot use 'in' operator to search for 'navigator' in undefined
  at isSupported (/Users/snoo/Dev/Nuxt/nodepicker/node_modules/sendbeacon-polyfill/dist/sendbeacon-polyfill.cjs.js:58:22)
  at polyfill (/Users/snoo/Dev/Nuxt/nodepicker/node_modules/sendbeacon-polyfill/dist/sendbeacon-polyfill.cjs.js:28:19)
  at Object.<anonymous> (/Users/snoo/Dev/Nuxt/nodepicker/node_modules/sendbeacon-polyfill/dist/sendbeacon-polyfill.cjs.js:25:10)
  at Module._compile (internal/modules/cjs/loader.js:689:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  at Module.require (internal/modules/cjs/loader.js:637:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at r (/Users/snoo/Dev/Nuxt/nodepicker/node_modules/vue-server-renderer/build.js:8341:16)
  at Object.sendbeacon-polyfill (server-bundle.js:20422:18)
  at __webpack_require__ (server-bundle.js:27:30)
  at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./layouts/default.vue?vue&type=script&lang=js& (server-bundle.js:6029:77)
  at __webpack_require__ (server-bundle.js:27:30)
  at Module../layouts/default.vue?vue&type=script&lang=js& (server-bundle.js:4110:198)
```

**Comment by miguelmota** [comment]
@SnooHD pushed an update. Try the latest release and let us know if it's not working still. The bug was that `window` and `this` was `undefined` which makes sense if it's using node to compile but should work once it's loaded into the browser

**Comment by kronicker** [comment]
@miguelmota, this is actually the issue since with my PR we converted this from being both ponyfill and polyfill to just being polyfill. Maybe I should've warned you about that since it can be considered as a breaking change and we should've pushed that as a major release.
Also, this works when bundling with webpack or rollup since they handle window references.
That being said, I was thinking about making it as both polyfill and ponyfill by separating that into different directories you the usage could be
```js
// Ponyfill
import sendBeacon from 'navigator.sendBeacon';

// Polyfill
import 'navigator.sendBeacon/polyfill'
```
That is actually the way that most *big* polyfills work (like [fetch polyfill](https://github.com/developit/unfetch)).
If you're ok with that I'll make a PR as soon as I get some time?

**Comment by miguelmota** [comment]
@kronicker yes that'd be ideal since ponyfills are best practice (this lib was created 4 years ago before ponyfills were a thing) 

Any help is appreciated 🙏

**Comment by SnooHD** [comment]
The error still persists, please drop a comment here when the PR is added :)
Thanks for your efforts! @kronicker @miguelmota

PS: The error points towards this file and location:
![image](https://user-images.githubusercontent.com/14291499/47596392-6d5f9780-d95c-11e8-9447-3cefc20bad00.png)

**Comment by miguelmota** [comment]
@SnooHD ah sorry, forgot to push the build yesterday. 0.0.14 should not give you the error https://npm.runkit.com/navigator.sendbeacon

**Comment by SnooHD** [comment]
haha, i should have realized that..
Anyways, yes, you're right! The error is gone 😃
Thank you kindly! ❤️
